[target.'cfg(target_arch = "wasm32")']
runner = 'cargo run -p wasm-bindgen-cli --bin wasm-bindgen-test-runner --'

[build]
rustflags = [
    #"-Clink-arg-bin=emcc=-sERROR_ON_UNDEFINED_SYMBOLS=0",
    "-Cllvm-args=-enable-emscripten-cxx-exceptions=0",  
    "-Clink-arg=-Wno-undefined",                                                                                                                                                                                                                 
]
